
package Finals;

/**
 *
 * @author Dell
 */
public class RecommendationTestFrame extends javax.swing.JFrame {

    /**
     * Creates new form RecommendationTestFrame
     */
    public RecommendationTestFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        QuestionsPanel = new javax.swing.JPanel();
        lblQ1 = new javax.swing.JLabel();
        rbTech = new javax.swing.JRadioButton();
        rbBusiness = new javax.swing.JRadioButton();
        rbHumanities = new javax.swing.JRadioButton();
        lblQ2 = new javax.swing.JLabel();
        cbMath = new javax.swing.JCheckBox();
        cbEnglish = new javax.swing.JCheckBox();
        cbICT = new javax.swing.JCheckBox();
        cbResearch = new javax.swing.JCheckBox();
        cbSocialScience = new javax.swing.JCheckBox();
        lblQ3 = new javax.swing.JLabel();
        rbBeginner = new javax.swing.JRadioButton();
        rbIntermediate = new javax.swing.JRadioButton();
        rbAdvanced = new javax.swing.JRadioButton();
        lblQ4 = new javax.swing.JLabel();
        rbLight = new javax.swing.JRadioButton();
        rbModerate = new javax.swing.JRadioButton();
        rbFullLoad = new javax.swing.JRadioButton();
        ButtonPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeaderPanel.setBackground(new java.awt.Color(0, 204, 255));
        HeaderPanel.setPreferredSize(new java.awt.Dimension(900, 115));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setText("Academic Recommendation Assessment");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/course-logo (1).png"))); // NOI18N
        lblLogo.setText("jLabel1");

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblTitle)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblLogo)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(33, 33, 33))
        );

        QuestionsPanel.setBackground(new java.awt.Color(255, 255, 255));
        QuestionsPanel.setPreferredSize(new java.awt.Dimension(900, 450));

        lblQ1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQ1.setForeground(new java.awt.Color(0, 0, 0));
        lblQ1.setText("1. What field are you most interested in?");

        rbTech.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbTech.setText("Technology");

        rbBusiness.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbBusiness.setText("Business");

        rbHumanities.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbHumanities.setText("Humanities");

        lblQ2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQ2.setForeground(new java.awt.Color(0, 0, 0));
        lblQ2.setText("2. Which subjects do you excel at?");

        cbMath.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbMath.setText("Math");
        cbMath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMathActionPerformed(evt);
            }
        });

        cbEnglish.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbEnglish.setText("English");

        cbICT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbICT.setText("ICT");

        cbResearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbResearch.setText("Research");
        cbResearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbResearchActionPerformed(evt);
            }
        });

        cbSocialScience.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbSocialScience.setText("Social Science");

        lblQ3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQ3.setForeground(new java.awt.Color(0, 0, 0));
        lblQ3.setText("3. Preferred course difficulty:");

        rbBeginner.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbBeginner.setText("Beginner");

        rbIntermediate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbIntermediate.setText("Intermediate");
        rbIntermediate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIntermediateActionPerformed(evt);
            }
        });

        rbAdvanced.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbAdvanced.setText("Advanced");

        lblQ4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQ4.setForeground(new java.awt.Color(0, 0, 0));
        lblQ4.setText("4. Preferred credit load per semester:");

        rbLight.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbLight.setText("Light (9-12 units)");
        rbLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLightActionPerformed(evt);
            }
        });

        rbModerate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbModerate.setText("Moderate (12-18 units)");
        rbModerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbModerateActionPerformed(evt);
            }
        });

        rbFullLoad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbFullLoad.setText("Full Load (18-24 units)");

        javax.swing.GroupLayout QuestionsPanelLayout = new javax.swing.GroupLayout(QuestionsPanel);
        QuestionsPanel.setLayout(QuestionsPanelLayout);
        QuestionsPanelLayout.setHorizontalGroup(
            QuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionsPanelLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(cbICT)
                .addGap(45, 45, 45)
                .addComponent(cbMath)
                .addGap(84, 84, 84)
                .addComponent(cbEnglish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(cbSocialScience)
                .addGap(112, 112, 112))
            .addGroup(QuestionsPanelLayout.createSequentialGroup()
                .addGroup(QuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuestionsPanelLayout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(cbResearch))
                    .addGroup(QuestionsPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(QuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQ3)
                            .addComponent(lblQ4)
                            .addGroup(QuestionsPanelLayout.createSequentialGroup()
                                .addGroup(QuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(QuestionsPanelLayout.createSequentialGroup()
                                        .addComponent(lblQ2)
                                        .addGap(49, 49, 49))
                                    .addGroup(QuestionsPanelLayout.createSequentialGroup()
                                        .addComponent(rbTech)
                                        .addGap(34, 34, 34)
                                        .addComponent(rbBusiness, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)))
                                .addComponent(rbHumanities))))
                    .addGroup(QuestionsPanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(rbAdvanced)
                        .addGap(73, 73, 73)
                        .addComponent(rbBeginner)
                        .addGap(58, 58, 58)
                        .addComponent(rbIntermediate))
                    .addGroup(QuestionsPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblQ1))
                    .addGroup(QuestionsPanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(QuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbModerate)
                            .addGroup(QuestionsPanelLayout.createSequentialGroup()
                                .addComponent(rbLight)
                                .addGap(76, 76, 76)
                                .addComponent(rbFullLoad)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuestionsPanelLayout.setVerticalGroup(
            QuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionsPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblQ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTech)
                    .addComponent(rbBusiness)
                    .addComponent(rbHumanities))
                .addGap(28, 28, 28)
                .addComponent(lblQ2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbICT)
                    .addComponent(cbMath)
                    .addComponent(cbEnglish)
                    .addComponent(cbResearch)
                    .addComponent(cbSocialScience))
                .addGap(29, 29, 29)
                .addComponent(lblQ3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAdvanced)
                    .addComponent(rbBeginner)
                    .addComponent(rbIntermediate))
                .addGap(29, 29, 29)
                .addComponent(lblQ4)
                .addGap(18, 18, 18)
                .addGroup(QuestionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLight)
                    .addComponent(rbFullLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbModerate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ButtonPanel.setBackground(new java.awt.Color(255, 255, 255));
        ButtonPanel.setPreferredSize(new java.awt.Dimension(900, 123));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("GENERATE RECOMMENDATION");

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelLayout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(251, 251, 251))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuestionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(QuestionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        HeaderPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbIntermediateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIntermediateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbIntermediateActionPerformed

    private void cbResearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbResearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbResearchActionPerformed

    private void rbModerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbModerateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbModerateActionPerformed

    private void cbMathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMathActionPerformed

    private void rbLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecommendationTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecommendationTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecommendationTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecommendationTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecommendationTestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel QuestionsPanel;
    private javax.swing.JCheckBox cbEnglish;
    private javax.swing.JCheckBox cbICT;
    private javax.swing.JCheckBox cbMath;
    private javax.swing.JCheckBox cbResearch;
    private javax.swing.JCheckBox cbSocialScience;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblQ1;
    private javax.swing.JLabel lblQ2;
    private javax.swing.JLabel lblQ3;
    private javax.swing.JLabel lblQ4;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbAdvanced;
    private javax.swing.JRadioButton rbBeginner;
    private javax.swing.JRadioButton rbBusiness;
    private javax.swing.JRadioButton rbFullLoad;
    private javax.swing.JRadioButton rbHumanities;
    private javax.swing.JRadioButton rbIntermediate;
    private javax.swing.JRadioButton rbLight;
    private javax.swing.JRadioButton rbModerate;
    private javax.swing.JRadioButton rbTech;
    // End of variables declaration//GEN-END:variables
}
